public class CountingPractice2{
	public static void main(String[]args){

		int x = 0;

		System.out.println("number\tsquare\tcube\t");

		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);
		x++;
		System.out.println(x + "\t" + x*x + "\t" + x*x*x);

	}
}